### ISSUE TITLE
Can not build with openssl 1.1.1a

### ISSUE THREAD

**Issue by xseven007** [chengr28/Pcap_DNSProxy#406]
﻿### Version/使用的版本/使用的版本
last github commit

### Running Environment/运行环境/運行環境
ubuntu 18.04 openssl 1.1.1a

### Actual/实际情况/實際情況

/usr/local/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
dso_dlfcn.c:(.text+0x11): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libpthread.a(nptl-init.o): In function `__pthread_initialize_minimal_internal':
/build/glibc-OTsEL5/glibc-2.27/nptl/nptl-init.c:294: undefined reference to `_dl_cpuclock_offset'
/build/glibc-OTsEL5/glibc-2.27/nptl/nptl-init.c:429: undefined reference to `_dl_pagesize'
/build/glibc-OTsEL5/glibc-2.27/nptl/nptl-init.c:438: undefined reference to `_dl_pagesize'
/build/glibc-OTsEL5/glibc-2.27/nptl/nptl-init.c:454: undefined reference to `_dl_init_static_tls'
/build/glibc-OTsEL5/glibc-2.27/nptl/nptl-init.c:456: undefined reference to `_dl_wait_lookup_done'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libpthread.a(nptl-init.o): In function `__pthread_get_minstack':
/build/glibc-OTsEL5/glibc-2.27/nptl/nptl-init.c:475: undefined reference to `_dl_pagesize'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libpthread.a(pthread_create.o): In function `allocate_stack':
/build/glibc-OTsEL5/glibc-2.27/nptl/allocatestack.c:526: undefined reference to `_dl_stack_flags'
/build/glibc-OTsEL5/glibc-2.27/nptl/allocatestack.c:652: undefined reference to `_dl_stack_flags'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libpthread.a(pthread_getattr_np.o): In function `pthread_getattr_np':
/build/glibc-OTsEL5/glibc-2.27/nptl/pthread_getattr_np.c:99: undefined reference to `_dl_pagesize'
/build/glibc-OTsEL5/glibc-2.27/nptl/pthread_getattr_np.c:137: undefined reference to `_dl_pagesize'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libpthread.a(elision-lock.o): In function `do_set_elision_enable':
/build/glibc-OTsEL5/glibc-2.27/nptl/../sysdeps/unix/sysv/linux/x86/elision-conf.c:67: undefined reference to `_dl_x86_cpu_features'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libdl.a(dlopen.o): In function `dlopen':
(.text+0x5): undefined reference to `__dlopen'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libdl.a(dlclose.o): In function `dlclose':
(.text+0x1): undefined reference to `__dlclose'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libdl.a(dlsym.o): In function `dlsym':
(.text+0x5): undefined reference to `__dlsym'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libdl.a(dlerror.o): In function `dlerror':
(.text+0x1): undefined reference to `__dlerror'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libdl.a(dladdr.o): In function `dladdr':
(.text+0x1): undefined reference to `__dladdr'
collect2: error: ld returned 1 exit status

**Comment by chengr28** [comment]
需要静态链接的话，可以在运行 `CMake_Build.sh` 的时候加上 `--enable-static` 看看，这个看起来是库的问题。

**Comment by xseven007** [comment]
就是使用静态编译导致错误，用动态库的话，是可以不报错的。上一个4.9.12版本是可以静态编译的，用openssl1.1.0，虽然能编译，仍然是有警告。很奇怪。

**Comment by wongsyrone** [comment]
需要 dl 库，`-ldl`

**Comment by xseven007** [comment]
@wongsyrone 对的。我找了一些相关的资料，对于这种需要-lssl和-ldl。可能需要28小朋友在脚本里改

**Comment by wongsyrone** [comment]
dl需要在前面，可以试试 LDFLAG="-ldl -lpthread -lssl -lcrypto"

**Comment by wongsyrone** [comment]
被误导了，这些-l的应该写在LDLIBS里面，LDFLAGS是 -L 用的

**Comment by xseven007** [comment]
LDLIBS在CMakeLists里似乎没有直接去定义，但是原来的CMakeLists里有
‘
IF(STATIC_LIB)
		find_library(LIBDL_LIBRARIES dl)
		target_link_libraries(Pcap_DNSProxy ${LIBDL_LIBRARIES})
		find_library(LIBZ_LIBRARIES z)
		target_link_libraries(Pcap_DNSProxy ${LIBZ_LIBRARIES})
	ENDIF(STATIC_LIB)
’

**Comment by chengr28** [comment]
如果还有更新的情况可以直接回复，谢谢。
